[project]
name = "iterable-io"
version = "1.0.2"
description = "Adapt generators and other iterables to a file-like interface"
urls.repository = "https://github.com/pR0Ps/iterable-io"
urls.changelog = "https://github.com/pR0Ps/iterable-io/blob/master/CHANGELOG.md"
readme = "README.md"
license = "LGPL-3.0-only"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)"
]
requires-python = ">=3.5"
dependencies = []

[dependency-groups]
test = ["pytest", "pytest-cov"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/iterableio"]
